name: Orca IaC Scan Workflow
on:
  push:
    branches: [ "main" ]
      
  pull_request:
    branches: [ "main" ]
    
permissions: 
  actions: read
  contents: read
  checks: write
  issues: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  orca-iac_scan:
    name: Orca IaC Scan
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: slrk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Orca IaC Scan
        uses: orcasecurity/shiftleft-iac-action@v1
        id: orca_scan
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path: "./"
          show_annotations: true
          custom_controls: "cust-query/"
